### ISSUE TITLE
javac: invalid target release: 1.8

### ISSUE THREAD

**Issue by bertspaan** [histograph/core#10]
@rutgervanwilligen Hoe los ik dit op?

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project histograph-core: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: invalid target release: 1.8
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR] -> [Help 1]
```

**Comment by rutgervanwilligen** [comment]
Dat heeft te maken met je versie van javac -- er zit code in (try-with-resources) die alleen met java 1.7 en 1.8 werkt. Ik heb in `pom.xml` geprobeerd af te dwingen dat java 1.8 gebruikt wordt, maar het werkt ook prima met 1.7. Ik heb het vermoeden dat je Maven niet de juiste versie gebruikt (zie `mvn --version` en `echo $JAVA_HOME`). Aangezien je volgens mij wel 1.8 geinstalleerd hebt, zou je alleen nog je `$JAVA_HOME` moeten bijwerken, dat kan met `export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)`.

Ik zal echter de pom bijwerken zodat-ie 1.7 vereist, ik krijg foutmeldingen als ik dat weglaat.

**Comment by rutgervanwilligen** [comment]
Pom dwingt nu 1.7+ af. Check met `mvn -v` welke versie Maven gebruikt bij het compilen, dat wordt volgens mij gebaseerd op `$JAVA_HOME`. Readme aangepast. Ik laat deze issue open totdat het opgelost is!

**Comment by reinvantveer** [comment]
Docker bouwt nu expliciet op oracle java 1.8. Kan/moet die ook terug naar 1.7?

Met vriendelijke groet,

Rein van 't Veer
Technisch Projectmedewerker | Technical Officer

Aanwezig: ma-di-wo-vr
t: 070-3140324

---

Van: Rutger van Willigen [notifications@github.com]
Verzonden: zondag 22 februari 2015 14:02
Aan: histograph/core
Onderwerp: Re: [core] javac: invalid target release: 1.8 (#10)

Pom dwingt nu 1.7+ af. Check met mvn -v welke versie Maven gebruikt bij het compilen, dat wordt volgens mij gebaseerd op $JAVA_HOME. Readme aangepast. Ik laat deze issue open totdat het opgelost is!

**Comment by rutgervanwilligen** [comment]
Ha Rein, Java 8 was volgens mij alleen voor Tinkerpop3 nodig en zou dus nu ook niet meer nodig hoeven zijn.
