### ISSUE TITLE
Build simple REST API for graph traversal into Core

### ISSUE THREAD

**Issue by bertspaan** [histograph/core#13]
See if it's a good idea to build an API for BFS graph traversals directly into Core using Neo4j's [Traversal API](http://neo4j.com/docs/stable/tutorials-java-embedded-traversal.html) (instead of using Cypher).

Maybe use [Play Framework](https://www.playframework.com/documentation/2.3.x/ScalaJsonHttp), or some other Java framework to create REST APIs?? :confused:

**Comment by bertspaan** [comment]
@rutgervanwilligen Let me know what you think, and let's build this together! I want to do some Java-ing too!

**Comment by bertspaan** [comment]
Of http://restx.io/?!?!

**Comment by bertspaan** [comment]
Or [Jersey](https://jersey.java.net/documentation/latest/getting-started.html)...

**Comment by bertspaan** [comment]
Core's Traversal API should respond to POST requests with the following JSON body:

``` json
{
  "hgids": [
    "tgn/219",
    "bag/bussum"
  ],
  "params": {

  }
}
```

**Comment by rutgervanwilligen** [comment]
Hatsaaaa. Alleen 'params' wordt nog niet gebruikt, maar is ook (nog?) niet nodig.
