### ISSUE TITLE
Traversal API should not return concepts/features with 0 geometries

### ISSUE THREAD

**Issue by bertspaan** [histograph/core#16]
Traversal API should not return concepts/features with 0 geometries. Graph traversals that do not encounter a PIT with a geometry should be discarded.

**Comment by rutgervanwilligen** [comment]
Zorgt er alleen wel direct ook voor dat bijv. de verdwenen dorpen niet meer gevonden worden.

**Comment by bertspaan** [comment]
Die hebben toch juist wél een geometrie? Bovendien, ik vind ze gewoon wel:

[http://localhost:4000/#name=naruthi](http://localhost:4000/#name=naruthi)

**Comment by rutgervanwilligen** [comment]
woeps, je hebt gelijk, ik bedoelde de militieregisters. Bijvoorbeeld als je zoekt naar "Blaricum N H": --> http://api.histograph.io/search?name=Blaricum%20N%20H

**Comment by bertspaan** [comment]
Ja maar die is ook niet gekoppeld aan andere PIT's, dus dat klopt!
