### ISSUE TITLE
Character/unicode error in tgn/7266359

### ISSUE THREAD

**Issue by bertspaan** [histograph/core#18]
PIT `tgn/7266359`:

``` json
{
    "name": "Heiloo�rbosschen",
    "hgid": "tgn/7266359",
    "source": "tgn",
    "geometryIndex": 0,
    "uri": "http://vocab.getty.edu/tgn/7266359"
}
```

Where does this error originate? In original data, in NDJSON, in IO, in Neo, or in Core?

**Comment by mmmenno** [comment]
In het csv-bestand ziet het er goed uit "http://vocab.getty.edu/tgn/7266359","Heilooërbosschen","Noord-Holland"
