### ISSUE TITLE
Import GeoNames / TGN service to histograph.io

### ISSUE THREAD

**Issue by rutgervanwilligen** [histograph/core#23]
Service should be used to import PiTs that are referenced by URI in a different dataset, but are not found in the datasets. For example, Simon Hart references Danish places -- these are not imported in the GeoNames dataset because only Dutch places are imported. With this service, however, because the Simon Hart dataset refers to this URI, we can get all details for the object associated with this URI.

**Comment by mmmenno** [comment]
Zie https://gist.github.com/mmmenno/df48ce69a5c4574e08d6

**Comment by bertspaan** [comment]
No!
