### ISSUE TITLE
Create program that clears index, textlogs and graphdb based on config

### ISSUE THREAD

**Issue by rutgervanwilligen** [histograph/core#26]
Perhaps this eases a total restart, and a bit more efficiently/robustly than shell scripts.

**Comment by reinvantveer** [comment]
This already exists: isn't this the same as [histograph-reload.sh](https://github.com/histograph/deploy/blob/master/histograph-reload.sh)? What would you have altered?

**Comment by rutgervanwilligen** [comment]
Yes, I forgot about this one. I figured it would be better to a) base it on the configuration file parameters so it works on any setup, and b) separate the data preprocessing step. While testing and rebuilding, the data preprocessing is unnecessary and takes incredibly long. If you think it's the same work done twice, then I'll move this issue to `deploy`.

**Comment by reinvantveer** [comment]
Please move to deploy
