### ISSUE TITLE
Tests, tests, tests, tests, tests, tests!

### ISSUE THREAD

**Issue by bertspaan** [histograph/core#30]
@rutgervanwilligen: write them!

**Comment by rutgervanwilligen** [comment]
Beginnetje gemaakt voor de GraphMethods. Overigens zijn deze weer uitgebreid (TODO's staan in de broncode) na het maken van de tests, dus die moeten nog bijgewerkt worden.
- [ ] Graph
- [ ] PSQL (ook belangrijk: sanitizing OK?)
- [ ] Elasticsearch
- [ ] Redis input simuleren middels ndjson bestanden in `test/resources` map, of afdwingen bij het testen Redis te laten draaien
- [ ] Combinatietests die de workflow van het hele programma valideren
