### ISSUE TITLE
Process Redis queue, create/delete/update vertices & edges

### ISSUE THREAD

**Issue by bertspaan** [histograph/core#4]
Process Redis queue, create/delete/update vertices & edges
- [x] Create vertices
- [x] Create edges
- [x] Delete vertices
- [x] Delete edges
- [x] Update vertices

**Comment by rutgervanwilligen** [comment]
Het updaten van edges is moeilijk omdat ze geen hgID hebben. Bij het updaten worden namelijk alleen de nieuwe waarden (label, vertexOUT en vertexIN) meegegeven, waardoor de originele edge niet meer te vinden is (wat is er veranderd? Bij een veranderde vertex nemen we aan dat de hgID identiek blijft, namelijk).
