### ISSUE TITLE
Vertices index (on hgid)

### ISSUE THREAD

**Issue by rutgervanwilligen** [histograph/core#5]

**Comment by bertspaan** [comment]
@rutgervanwilligen And [Lucene-index](http://jexp.de/blog/2014/03/full-text-indexing-fts-in-neo4j-2-0/) on `name` field!

**Comment by rutgervanwilligen** [comment]
Elasticsearch ipv Lucene...?

**Comment by rutgervanwilligen** [comment]
hgID index werkt als een tiet. Voor nu ook een Neo4j schema index op `name`, die moet later evt. nog worden uitbesteed aan Elasticsearch. Voor nu vind ik 't closed.
