### ISSUE TITLE
Suspicious `x = y` without link to `:=` node

### ISSUE THREAD

**Issue by wires** [histograph/core#50]
investigate why this _Friens_ guy isn't linked to the red node ...

![image](https://cloud.githubusercontent.com/assets/315734/9185302/00875fb4-3fbb-11e5-8561-7cf43ebe1b32.png)

**Comment by jobspierings** [comment]
Suggest to close until issue pops up again, @wires ok?

**Comment by sbocconi** [comment]
Transferred  to Graphmalizer https://github.com/graphmalizer/graphmalizer-core/issues/22
