### ISSUE TITLE
Locatie en opzet database

### ISSUE THREAD

**Issue by rutgervanwilligen** [histograph/core#7]
De locatie van de database moet bepaald worden. Zoals ik het zie, zijn er twee mogelijkheden:

1) Extern, buiten het core javaprogramma.
- Voordelen:
  - Mogelijkheid meerdere connecties te maken (een vanuit `core`, de ander vanuit de `api`, dus simultaan updaten en querien mogelijk.
  - Grafische interface van Neo4j aan te roepen (localhost:7474), hoewel dat eigenlijk alleen voor testing purposes praktisch is.
- Nadelen: 
  - Communicatie-overhead met communiceren vanaf `core`, alle mutaties moeten dan van client naar server verstuurd worden.
  - Direct de graaf muteren met java library om dezelfde reden ook niet mogelijk.

2) Binnen in het core javaprogramma
- Voordelen:
  - Geen communicatie-overhead, directe graafmutaties ook mogelijk (waarschijnlijk)
- Nadelen:
  - Database moet opgezet worden en simultaan in het javaprogramma draaien. Dat houdt waarschijnlijk in dat we zelf de database calls moeten opvangen en als directe graafquery moeten uitvoeren. Bij het gebruik van serverlibraries gaat anders waarschijnlijk hetzelfde probleem ontstaan als bij de externe server: geen twee verbindingen simultaan toegestaan.

**Comment by rutgervanwilligen** [comment]
`WrappingNeoServerBootstrapper` ingevoegd. Deze class is echter deprecated (wordt waarschijnlijk bij Neo4j release 3.0.0+ weggehaald, in het slechtste geval al eerder), maar er zijn geen alternatieven te vinden op dit moment. Deze oplossing wordt vaker gebruikt en voor nu werkt het prima.

**Comment by bertspaan** [comment]
:dancers:
